@endpoint = https://dev.azure.com/
@organization = jannemattilademo
# base64(":" + pat)
@auth = pat

### Fetch projects
# @name projects
GET {{endpoint}}{{organization}}/_apis/projects?api-version=2.0 HTTP/1.1
Content-type: application/json
Authorization: Basic {{auth}}

### Fetch first project information
# @name project
@projectId = {{project.response.body.id}}
GET {{endpoint}}{{organization}}/_apis/projects/{{projectId}}?api-version=2.0 HTTP/1.1
Content-type: application/json
Authorization: Basic {{auth}}

### Fetch git repositories of project
# @name repositories
@projectId = {{project.response.body.id}}
GET {{endpoint}}{{organization}}/{{projectId}}/_apis/git/repositories?api-version=6.0-preview.1 HTTP/1.1
Content-type: application/json
Authorization: Basic {{auth}}
